PROG2PRY1/Controllers/T_CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PROG2PRY1.Models;

namespace PROG2PRY1.Controllers
{
    public class T_CategoriaController : Controller
    {
        private Entities db = new Entities();

        public ActionResult Index()
        {
            return View(db.T_Categoria.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Categoria t_Categoria = db.T_Categoria.Find(id);
            if (t_Categoria == null)
            {
                return HttpNotFound();
            }
            return View(t_Categoria);
        }

        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Descripion")] T_Categoria t_Categoria)
        {
            if (ModelState.IsValid)
            {
                db.T_Categoria.Add(t_Categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(t_Categoria);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Categoria t_Categoria = db.T_Categoria.Find(id);
            if (t_Categoria == null)
            {
                return HttpNotFound();
            }
            return View(t_Categoria);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Descripion")] T_Categoria t_Categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(t_Categoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(t_Categoria);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Categoria t_Categoria = db.T_Categoria.Find(id);
            if (t_Categoria == null)
            {
                return HttpNotFound();
            }
            return View(t_Categoria);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Categoria t_Categoria = db.T_Categoria.Find(id);
            db.T_Categoria.Remove(t_Categoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROG2PRY1/Controllers/T_ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PROG2PRY1.Models;

namespace PROG2PRY1.Controllers
{
    public class T_ClientesController : Controller
    {
        private Entities db = new Entities();

        public ActionResult Index()
        {
            return View(db.T_Clientes.ToList());
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Clientes t_Clientes = db.T_Clientes.Find(id);
            if (t_Clientes == null)
            {
                return HttpNotFound();
            }
            return View(t_Clientes);
        }

        
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Apellido,Telefono")] T_Clientes t_Clientes)
        {
            if (ModelState.IsValid)
            {
                db.T_Clientes.Add(t_Clientes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(t_Clientes);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Clientes t_Clientes = db.T_Clientes.Find(id);
            if (t_Clientes == null)
            {
                return HttpNotFound();
            }
            return View(t_Clientes);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Apellido,Telefono")] T_Clientes t_Clientes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(t_Clientes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(t_Clientes);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Clientes t_Clientes = db.T_Clientes.Find(id);
            if (t_Clientes == null)
            {
                return HttpNotFound();
            }
            return View(t_Clientes);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Clientes t_Clientes = db.T_Clientes.Find(id);
            db.T_Clientes.Remove(t_Clientes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROG2PRY1/Controllers/T_ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PROG2PRY1.Models;

namespace PROG2PRY1.Controllers
{
    public class T_ProductosController : Controller
    {
        private Entities db = new Entities();

        public ActionResult Index()
        {
            var t_Productos = db.T_Productos.Include(t => t.T_Categoria).Include(t => t.T_Clientes);
            return View(t_Productos.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Productos t_Productos = db.T_Productos.Find(id);
            if (t_Productos == null)
            {
                return HttpNotFound();
            }
            return View(t_Productos);
        }

        public ActionResult Create()
        {
            ViewBag.ID_Categoria = new SelectList(db.T_Categoria, "ID", "Descripion");
            ViewBag.ID_Cliente = new SelectList(db.T_Clientes, "ID", "Nombre");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Precio,ID_Categoria,ID_Cliente")] T_Productos t_Productos)
        {
            if (ModelState.IsValid)
            {
                db.T_Productos.Add(t_Productos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Categoria = new SelectList(db.T_Categoria, "ID", "Descripion", t_Productos.ID_Categoria);
            ViewBag.ID_Cliente = new SelectList(db.T_Clientes, "ID", "Nombre", t_Productos.ID_Cliente);
            return View(t_Productos);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Productos t_Productos = db.T_Productos.Find(id);
            if (t_Productos == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Categoria = new SelectList(db.T_Categoria, "ID", "Descripion", t_Productos.ID_Categoria);
            ViewBag.ID_Cliente = new SelectList(db.T_Clientes, "ID", "Nombre", t_Productos.ID_Cliente);
            return View(t_Productos);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Precio,ID_Categoria,ID_Cliente")] T_Productos t_Productos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(t_Productos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Categoria = new SelectList(db.T_Categoria, "ID", "Descripion", t_Productos.ID_Categoria);
            ViewBag.ID_Cliente = new SelectList(db.T_Clientes, "ID", "Nombre", t_Productos.ID_Cliente);
            return View(t_Productos);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Productos t_Productos = db.T_Productos.Find(id);
            if (t_Productos == null)
            {
                return HttpNotFound();
            }
            return View(t_Productos);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Productos t_Productos = db.T_Productos.Find(id);
            db.T_Productos.Remove(t_Productos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROG2PRY1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Scripts/src/custome-style.css" />
</head>
<body style="background-color: #F5F5DC;">


    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Clientekks", "Index", "T_Clientes", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @Html.ActionLink("Productos", "Create", "T_Productos", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Categorias", "Create", "T_Categoria", new { area = "" }, new { @class = "navbar-brand" })

                    </ul>
                </div>
            </div>
        </div>*@


    @*********************PROBANDO NEW  NAVEGATION BAR***************@

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F5F5DC;">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                @*<a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="#">Features</a>
                    <a class="nav-item nav-link" href="#">Pricing</a>
                    <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>*@
                <ul class="nav navbar-nav" style="font-weight: 900 ;">
                    @Html.ActionLink("Clientes", "Index", "T_Clientes", new { area = "" }, new { @class = "navbar-brand nav-item nav-link" })
                    @Html.ActionLink("Productos", "Index", "T_Productos", new { area = "" }, new { @class = "navbar-brand nav-item nav-link" })
                    @Html.ActionLink("Categorias", "Index", "T_Categoria", new { area = "" }, new { @class = "navbar-brand nav-item nav-link" })

                </ul>

                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
                </form>

            </div>
        </div>
    </nav>

    @*********************PROBANDO NEW  NAVEGATION BAR***************@


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ibis Ruiz 2017-4572 || Alfredo Linarez 2017-4800</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>